[functions]
directory = "src/functions"

[functions."welcome-new-user"]
schedule = "*/5 * * * *"
# schedule = "@hourly"

# [build]
#   command = "npm run build"
#   publish = "dist_website/"
#   functions = "dist_functions/"
